### PR TITLE
prevent default when clicking on lnurls.

### PR DESCRIPTION
**Pull request by fiatjaf**

### CODE REVIEW

**Review by pseudozach — APPROVED** [review]
no idea what I'm doing

**Comment by pseudozach** [comment]
patch-2 covers this one too I think, so closing this one. let me know otherwise.

**Comment by fiatjaf** [comment]
It doesn't! It's a different thing!

**Comment by pseudozach** [comment]
Sorry. I'll merge and test again.
Firefox is not working anyways.

**Pull request merged**
